# Generated by Django 5.2.8 on 2025-12-08 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount_vnd', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'Đã thanh toán, chưa gán trạm'), ('assigned', 'Đã gán trạm/cổng, chờ ESP32 xử lý'), ('charging', 'Đang sạc'), ('done', 'Hoàn tất'), ('waiting', 'Chờ slot trống')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.chargerdevice')),
            ],
        ),
    ]
