# Generated by Django 5.2.9 on 2025-12-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chargerport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingsession',
            name='status',
            field=models.CharField(choices=[('paid', 'Đã thanh toán, chưa gán trạm'), ('assigned', 'Đã gán trạm/cổng, đang sạc '), ('done', 'Hoàn tất')], max_length=20),
        ),
    ]
